backend:
  name: github
  repo: endymion1818/freeb5-gatsbyjs
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"
collections:

  - name: "post"
    label: "Post"
    folder: "src/pages/post"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "categories", widget: "array" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
