backend:
  name: git-gateway
  repo: endymion1818/freeb5-gatsbyjs
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"
collections: posts

  - name: "post"
    label: "Post"
    folder: "src/pages/post"
    create: true
    extension: "md"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
